# -*- coding: utf-8 -*-
"""UNIT5 - Practice Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0Fwzodk3ephKYAe3lJso-vGe7AqlPTK

## Unit 5 practice Program
"""

# Program 1: Simple Rule-Based Chatbot using NLTK
import nltk
from nltk.chat.util import Chat, reflections

# Define conversation patterns
pairs = [
    (r"hi|hello|hey",
     ["Hello! How can I help you?",
      "Hi there! What can I do for you?"]),

    (r"what is your name?",
     ["I am Jason, your virtual assistant.",
      "My name is Jason!"]),

    (r"how are you?",
     ["I'm doing great, thank you!",
      "I'm fine. How about you?"]),

    (r"what can you do?",
     ["I can answer basic questions and have a conversation!"]),

    (r"tell me about (.*)",
     ["Sure! %1 is a very interesting topic.",
      "I know a bit about %1! What would you like to know?"]),

    (r"quit|bye|exit",
     ["Goodbye! Have a great day!",
      "Bye! Come back soon."]),

    (r"(.*)",
     ["I'm not sure I understand. Could you rephrase?",
      "Interesting! Tell me more."]),
]

def chatbot():
    print("Chatbot: Hello! I am Jason. Type 'quit' to exit.")
    chat = Chat(pairs, reflections)
    chat.converse()

if __name__ == "__main__":
    chatbot()

# Program 2: AI Chatbot using DialoGPT (Transformers)
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model     = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

print("DialoGPT Chatbot started. Type 'quit' to exit.\n")

chat_history_ids = None   # stores conversation context

for step in range(6):     # allow 6 conversation turns
    user_input = input("You: ")
    if user_input.lower() in ["quit", "exit", "bye"]:
        print("Bot: Goodbye! Have a nice day!")
        break

    # Encode new user input + EOS token
    new_input_ids = tokenizer.encode(
        user_input + tokenizer.eos_token, return_tensors="pt"
    )

    # Append to chat history
    bot_input_ids = (
        torch.cat([chat_history_ids, new_input_ids], dim=-1)
        if chat_history_ids is not None else new_input_ids
    )

    # Generate response
    chat_history_ids = model.generate(
        bot_input_ids, max_length=1000,
        pad_token_id=tokenizer.eos_token_id,
        no_repeat_ngram_size=3, do_sample=True,
        top_k=50, top_p=0.92, temperature=0.75,
    )

    # Decode only the new response
    response = tokenizer.decode(
        chat_history_ids[:, bot_input_ids.shape[-1]:][0],
        skip_special_tokens=True

    )